### ISSUE TITLE
20210808-Ipv6-Mini-x86-64 版本unblockneteasemusic启动失败

### ISSUE THREAD

**Issue by zzz6839** [sirpdboy/openwrt18.06#177]
问题复现：
更新组件>更新主程序>主程序更新完成>启用插件>未运行>日志

/usr/share/unblockneteasemusic/core/src/hook.js:409
		if ((item.code != 200 || item.freeTrialInfo || item.br < 320000) && (target == 0 || item.id == target)) {
		^^

SyntaxError: Unexpected token 'if'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/src/app.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by zzz6839** [comment]
我有回滚openwrt版本到2021年6月10号的稳定版本，但是一样会出现这个问题

**Comment by zzz6839** [comment]
解决了，思路：

卸载当前版本 opkg remove luci-app-unblockneteasemusic +版本
卸载核心 cd /
                 rm -rf usr/share/unblockneteasemusic/core
安装最新版本  opkg install luci-app-unblockneteasemusic + 最新版本
然后到相关页面更新核心就可以了
